services:
  sakani-api:
    image: sakani_api:latest # استبدل باسم الصورة الخاصة بك
    container_name: sakani_api_prod
    restart: always
    ports:
      - "80:8080" 
    env_file:
      - .env.production