services:
  postgres_db:
    image: postgres:16-alpine
    container_name: realestate_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyPassword1234
      POSTGRES_DB: Sakani
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: